# The name of benchmarking/config using TPBench BenchScore mode
ConfigAttributes: 
  name: default
  description: Default configuration for TPBench.
  version: 1.0.0
  date: 2025-07-11

# Settings of memory layers.
# Format:
#   name: the name of the memory layer.
#   size: the size of the memory layer in KiB.
#   sharedby: the number of cores that share this memory layer.
Hardware:
  memory_layers:
    - name: L1
      size: 32
      sharedby: 1
    - name: L2
      size: 256
      sharedby: 1
    - name: L3
      size: 12288
      sharedby: 1

Dependency:
  base_cc:
    command: gcc
    path: /usr
    cflags: ['-O3', '-fno-builtin', '-march=native', '-mtune=native']
  mpi_cc:
    command: mpicc
    path: /usr
    cflags: ['-O3', '-fno-builtin', '-march=native', '-mtune=native']
    ldflags: ['-lmpi']

# Run-time configuration.
Runtime:
  parallel:
    # Choose a backend for parallel benchmarks, default: serial.
    # Available backends:
    # - serial: serial backend
    # - mpi: MPI standard, following MPI-3.1 by default.
    backend: serial 
    # The number of nodes.
    num_node: 1
    # The number of processes per node.
    num_proc: 1
    # The number of threads per process.
    num_thread: 1
  timer:
    # The wall timer to use. default: clock_gettime.
    # Available timers:
    # - off: Turn OFF wall clock timer.
    # - cgt: clock_gettime
    # - rdtsc: X86 rdtsc instruction. This timer reads the TSC register. If use tsc, please note that
    #   TSC register often stays at a constant value even when the actual frequency is changing.
    # - cntvct: Armv8 CNTVCT instruction. This timer reads the CNTVCT register.
    wall_timer: cgt
    # The time per tick of the wall timer in nanoseconds.
    # Only used when wall_timer is rdtsc.
    wall_div_ns: 1
    # The cycle timer to use. default: rdtsc.
    # Available timers:
    # - off: Turn OFF cycle timer.
    # - auto: Auto-detect the cycle timer. If set, all settings related to cycle timer will be
    #   ignored.
    # - CPU_CLK_UNHALTED: X86 CPU_CLK_UNHALTED.CORE or CPU_CLK_UNHALTED.THREAD counter. This timer
    #   counts the actual physical frequency of the CPU, but requires the permission of user-
    #   level event access.
    # - pmccntr: Armv8 PMCCNTR instruction. This timer reads the PMCCNTR event. User-level event access
    #   is required.
    cycle_timer: auto
    # The number of cycles per second. default: 0.
    # If set to value other than 0, TPBench will use this value instead of auto-detecting it.
    cycle_per_sec: 0
  benchmark:
    default_num_loop: 10
    # Warm-up time for each kernel in seconds.
    default_warmup: 1
    # The number of warm-up iterations. default: 1.
    default_num_thread: 1
    batches:
      - name: default
        # Kernels to run in this group. Format:
        # - name: the name of the kernel.
        # - size: Array of the size of the initial data in KiB.
        # - args: the arguments of the kernel.
        kernels:
          - name: d_fmaldr
            args: 
              - size: [32, 64, 1024]
              - dtype: ['uint64', 'fp64']
              - arith_intensity: [0.25, 0.5, 0.75, 1.0, 2.0, 4.0, 8.0]
          - name: d_triad
            args: 
              - size: [32, 64, 1024]
              - dtype: ['uint64', 'fp64']