/**
 * @file tpb-unitdefs.h
 * @brief Macros for defining and controlling units of arguments, parameters and metrics.
 */

#ifndef TPB_UNITDEFS_H
#define TPB_UNITDEFS_H

#include <stdint.h>
#include <inttypes.h>

typedef uint64_t TPB_UNIT_T;

/*
 * Common Metric Unit Encoding (TPB_UNIT_T - 64-bit)
 *
 * Bit layout (from LSB to MSB):
 *   Bits 0-31  (0x00000000FFFFFFFF): Exponent OR Multiplier value
 *   Bits 32-35 (0x0000000F00000000): Base type (EXP vs MUL, BIN/DEC/OCT/HEX, P/N)
 *   Bits 36-43 (0x00000FF000000000): Unit name identifier
 *   Bits 44-47 (0x0000F00000000000): Unit kind (TIME, VOL, OPS)
 *   Bits 48-63 (0xFFFF000000000000): Attribution control bits
 *
 * Value interpretation by base type:
 *   - *_EXP_P: scale = base^value (positive exponent)
 *   - *_EXP_N: scale = base^(-value) (negative exponent)
 *   - *_MUL_P: scale = value (direct multiplier)
 */

/* All shifts below 32 are safe, but those >= 32 must use 1ULL for portability! */
#define TPB_UATTR_MASK               ((TPB_UNIT_T)0xFFFF000000000000)
#define TPB_UATTR_CAST_MASK          ((TPB_UNIT_T)(1ULL << 48)) 
#define TPB_UATTR_CAST_Y             ((TPB_UNIT_T)(1ULL << 48))
#define TPB_UATTR_CAST_N             ((TPB_UNIT_T)(0ULL << 48))
#define TPB_UATTR_SHAPE_MASK         ((TPB_UNIT_T)(7ULL << 49))     // Support up to 7-D array.
#define TPB_UATTR_SHAPE_POINT        ((TPB_UNIT_T)(0ULL << 49))     // Single-point data
#define TPB_UATTR_SHAPE_1D           ((TPB_UNIT_T)(1ULL << 49))     // 1D array
#define TPB_UATTR_SHAPE_2D           ((TPB_UNIT_T)(2ULL << 49))     // 2D array
#define TPB_UATTR_SHAPE_3D           ((TPB_UNIT_T)(3ULL << 49))     // 3D array
#define TPB_UATTR_SHAPE_4D           ((TPB_UNIT_T)(4ULL << 49))     // 4D array
#define TPB_UATTR_SHAPE_5D           ((TPB_UNIT_T)(5ULL << 49))     // 5D array
#define TPB_UATTR_SHAPE_6D           ((TPB_UNIT_T)(6ULL << 49))     // 6D array
#define TPB_UATTR_SHAPE_7D           ((TPB_UNIT_T)(7ULL << 49))     // 7D array

// A full unit name = UKIND&<name_code>
#define TPB_UKIND_MASK          ((TPB_UNIT_T)  0x0000F00000000000)
#define TPB_UKIND_UNDEF         ((TPB_UNIT_T)  0x0000000000000000)
#define TPB_UKIND_TIME          ((TPB_UNIT_T)  0x0000100000000000)
#define TPB_UKIND_VOL           ((TPB_UNIT_T)  0x0000200000000000)
#define TPB_UKIND_VOLPTIME      ((TPB_UNIT_T)  0x0000300000000000)   // VOL/time
#define TPB_UNAME_MASK           ((TPB_UNIT_T) 0x0000FFF000000000)
#define TPB_UNAME_UNDEF          ((TPB_UNIT_T) 0x0000000000000000)
#define TPB_UNAME_WALLTIME      (((TPB_UNIT_T) 0x0000001000000000) | TPB_UKIND_TIME)      // Wall-clock time
#define TPB_UNAME_PHYSTIME      (((TPB_UNIT_T) 0x0000002000000000) | TPB_UKIND_TIME)      // Chip physical time
#define TPB_UNAME_DATETIME      (((TPB_UNIT_T) 0x0000003000000000) | TPB_UKIND_TIME)      // Date time
#define TPB_UNAME_TICKTIME      (((TPB_UNIT_T) 0x0000004000000000) | TPB_UKIND_TIME)      // Tick
#define TPB_UNAME_TIMERTIME     (((TPB_UNIT_T) 0x0000005000000000) | TPB_UKIND_TIME)      // Time unit following the timer
#define TPB_UNAME_DATASIZE      (((TPB_UNIT_T) 0x0000001000000000) | TPB_UKIND_VOL)       // Data size
#define TPB_UNAME_OP            (((TPB_UNIT_T) 0x0000002000000000) | TPB_UKIND_VOL)       // Operation counts
#define TPB_UNAME_GRIDSIZE      (((TPB_UNIT_T) 0x0000003000000000) | TPB_UKIND_VOL)       // The number of grids.
#define TPB_UNAME_BITSIZE       (((TPB_UNIT_T) 0x0000004000000000) | TPB_UKIND_VOL)       // Binary bit size
#define TPB_UNAME_OPS           (((TPB_UNIT_T) 0x0000001000000000) | TPB_UKIND_VOLPTIME)  // Operation per second
#define TPB_UNAME_FLOPS         (((TPB_UNIT_T) 0x0000002000000000) | TPB_UKIND_VOLPTIME)  // Flop/s
#define TPB_UNAME_TOKENPS       (((TPB_UNIT_T) 0x0000003000000000) | TPB_UKIND_VOLPTIME)  // Token per second
#define TPB_UNAME_TPS           (((TPB_UNIT_T) 0x0000004000000000) | TPB_UKIND_VOLPTIME)  // Transaction per second
#define TPB_UNAME_BITPS         (((TPB_UNIT_T) 0x0000005000000000) | TPB_UKIND_VOLPTIME)  // bit/s, Byte/s, KiB/s, ...
#define TPB_UNAME_DATAPS        (((TPB_UNIT_T) 0x0000006000000000) | TPB_UKIND_VOLPTIME)  // Byte/s, KB/s, ...
#define TPB_UNAME_BITPCY        (((TPB_UNIT_T) 0x0000007000000000) | TPB_UKIND_VOLPTIME)  // bit/cy, Byte/cy, KiB/cy, ...
#define TPB_UNAME_DATAPCY       (((TPB_UNIT_T) 0x0000008000000000) | TPB_UKIND_VOLPTIME)  // Byte/cy, KB/cy, ...
#define TPB_UNAME_BITPTICK      (((TPB_UNIT_T) 0x0000009000000000) | TPB_UKIND_VOLPTIME)  // bit/tick, Byte/tick, KiB/tick, ...
#define TPB_UNAME_DATAPTICK     (((TPB_UNIT_T) 0x000000a000000000) | TPB_UKIND_VOLPTIME)  // Byte/tick, KB/tick, ...

// TPB_UBASE_BASE: This is a base unit.
// TPB_UBASE_<base_num>[BIN/DEC/...]_<convert_ops>[MUL/EXP]_<positive/nagative>[P/N]
#define TPB_UBASE_MASK          ((TPB_UNIT_T) 0x0000000F00000000)
#define TPB_UBASE_UNDEF         ((TPB_UNIT_T) 0x0000000000000000)
#define TPB_UBASE_BASE          ((TPB_UNIT_T) 0x0000000100000000)
#define TPB_UBASE_BIN_EXP_P     ((TPB_UNIT_T) 0x0000000200000000)
#define TPB_UBASE_BIN_EXP_N     ((TPB_UNIT_T) 0x0000000300000000)
#define TPB_UBASE_BIN_MUL_P     ((TPB_UNIT_T) 0x0000000400000000)
#define TPB_UBASE_OCT_EXP_P     ((TPB_UNIT_T) 0x0000000500000000)
#define TPB_UBASE_OCT_EXP_N     ((TPB_UNIT_T) 0x0000000600000000)
#define TPB_UBASE_DEC_EXP_P     ((TPB_UNIT_T) 0x0000000700000000)
#define TPB_UBASE_DEC_EXP_N     ((TPB_UNIT_T) 0x0000000800000000)
#define TPB_UBASE_DEC_MUL_P     ((TPB_UNIT_T) 0x0000000900000000)
#define TPB_UBASE_HEX_EXP_P     ((TPB_UNIT_T) 0x0000000a00000000)
#define TPB_UBASE_HEX_EXP_N     ((TPB_UNIT_T) 0x0000000b00000000)

#define TPB_UNIT_MASK           ((TPB_UNIT_T) 0x00000000FFFFFFFF)
#define TPB_UNIT_UNDEF          ((TPB_UNIT_T) 0x00000000FFFFFFFF)
// OP: The number of operations
#define TPB_UNIT_OP             (((TPB_UNIT_T)0)  | TPB_UNAME_OP | TPB_UBASE_BASE)
#define TPB_UNIT_KOP            (((TPB_UNIT_T)3)  | TPB_UNAME_OP | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MOP            (((TPB_UNIT_T)6)  | TPB_UNAME_OP | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GOP            (((TPB_UNIT_T)9)  | TPB_UNAME_OP | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TOP            (((TPB_UNIT_T)12) | TPB_UNAME_OP | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_POP            (((TPB_UNIT_T)15) | TPB_UNAME_OP | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_EOP            (((TPB_UNIT_T)18) | TPB_UNAME_OP | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZOP            (((TPB_UNIT_T)21) | TPB_UNAME_OP | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YOP            (((TPB_UNIT_T)24) | TPB_UNAME_OP | TPB_UBASE_DEC_EXP_P)
// Bit size
#define TPB_UNIT_BIT       (((TPB_UNIT_T)3)  | TPB_UNAME_BITSIZE | TPB_UBASE_BIN_EXP_N)
#define TPB_UNIT_BYTE      (((TPB_UNIT_T)0)  | TPB_UNAME_BITSIZE | TPB_UBASE_BASE)
#define TPB_UNIT_KIB       (((TPB_UNIT_T)10) | TPB_UNAME_BITSIZE | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_MIB       (((TPB_UNIT_T)20) | TPB_UNAME_BITSIZE | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_GIB       (((TPB_UNIT_T)30) | TPB_UNAME_BITSIZE | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_TIB       (((TPB_UNIT_T)40) | TPB_UNAME_BITSIZE | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_PIB       (((TPB_UNIT_T)50) | TPB_UNAME_BITSIZE | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_EIB       (((TPB_UNIT_T)60) | TPB_UNAME_BITSIZE | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_ZIB       (((TPB_UNIT_T)70) | TPB_UNAME_BITSIZE | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_YIB       (((TPB_UNIT_T)80) | TPB_UNAME_BITSIZE | TPB_UBASE_BIN_EXP_P)
// Data size
#define TPB_UNIT_B         (((TPB_UNIT_T)0)  | TPB_UNAME_DATASIZE | TPB_UBASE_BASE)
#define TPB_UNIT_KB        (((TPB_UNIT_T)3)  | TPB_UNAME_DATASIZE | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MB        (((TPB_UNIT_T)6)  | TPB_UNAME_DATASIZE | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GB        (((TPB_UNIT_T)9)  | TPB_UNAME_DATASIZE | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TB        (((TPB_UNIT_T)12) | TPB_UNAME_DATASIZE | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_PB        (((TPB_UNIT_T)15) | TPB_UNAME_DATASIZE | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_EB        (((TPB_UNIT_T)18) | TPB_UNAME_DATASIZE | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZB        (((TPB_UNIT_T)21) | TPB_UNAME_DATASIZE | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YB        (((TPB_UNIT_T)24) | TPB_UNAME_DATASIZE | TPB_UBASE_DEC_EXP_P)
// Wall clock time based on nanosecond
#define TPB_UNIT_NS        (((TPB_UNIT_T)0)  | TPB_UNAME_WALLTIME | TPB_UBASE_BASE)
#define TPB_UNIT_AS        (((TPB_UNIT_T)9)  | TPB_UNAME_WALLTIME | TPB_UBASE_DEC_EXP_N)
#define TPB_UNIT_FS        (((TPB_UNIT_T)6)  | TPB_UNAME_WALLTIME | TPB_UBASE_DEC_EXP_N)
#define TPB_UNIT_PS        (((TPB_UNIT_T)3)  | TPB_UNAME_WALLTIME | TPB_UBASE_DEC_EXP_N)
#define TPB_UNIT_US        (((TPB_UNIT_T)3)  | TPB_UNAME_WALLTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MS        (((TPB_UNIT_T)6)  | TPB_UNAME_WALLTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_SS        (((TPB_UNIT_T)9)  | TPB_UNAME_WALLTIME | TPB_UBASE_DEC_EXP_P)
// Physical tick/cycle
#define TPB_UNIT_CY        (((TPB_UNIT_T)0)  | TPB_UNAME_PHYSTIME | TPB_UBASE_BASE)
#define TPB_UNIT_KCY       (((TPB_UNIT_T)3)  | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MCY       (((TPB_UNIT_T)6)  | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GCY       (((TPB_UNIT_T)9)  | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TCY       (((TPB_UNIT_T)12) | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_PCY       (((TPB_UNIT_T)15) | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ECY       (((TPB_UNIT_T)18) | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZCY       (((TPB_UNIT_T)21) | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YCY       (((TPB_UNIT_T)24) | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
// Date time no macro-defined convert, !!!NOTE: Sidereal year, might be a little drifts to the calendar!!!
#define TPB_UNIT_SEC       (((TPB_UNIT_T)0)        | TPB_UNAME_DATETIME | TPB_UBASE_BASE)
#define TPB_UNIT_MIN       (((TPB_UNIT_T)60)       | TPB_UNAME_DATETIME | TPB_UBASE_DEC_MUL_P)
#define TPB_UNIT_HOU       (((TPB_UNIT_T)3600)     | TPB_UNAME_DATETIME | TPB_UBASE_DEC_MUL_P)
#define TPB_UNIT_DAY       (((TPB_UNIT_T)86400)    | TPB_UNAME_DATETIME | TPB_UBASE_DEC_MUL_P)
#define TPB_UNIT_MON       (((TPB_UNIT_T)2629846)  | TPB_UNAME_DATETIME | TPB_UBASE_DEC_MUL_P) // ~30.438days, calculated by S-year / 12 = 2629845.833
#define TPB_UNIT_YEA       (((TPB_UNIT_T)31558150) | TPB_UNAME_DATETIME | TPB_UBASE_DEC_MUL_P) // Sidereal year
// Any counter/vibrator tick
#define TPB_UNIT_TICK        (((TPB_UNIT_T)0)  | TPB_UNAME_PHYSTIME | TPB_UBASE_BASE)
#define TPB_UNIT_KTICK       (((TPB_UNIT_T)3)  | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MTICK       (((TPB_UNIT_T)6)  | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GTICK       (((TPB_UNIT_T)9)  | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TTICK       (((TPB_UNIT_T)12) | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_PTICK       (((TPB_UNIT_T)15) | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ETICK       (((TPB_UNIT_T)18) | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZTICK       (((TPB_UNIT_T)21) | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YTICK       (((TPB_UNIT_T)24) | TPB_UNAME_PHYSTIME | TPB_UBASE_DEC_EXP_P)
// Time unit set by the timer
#define TPB_UNIT_TIMER     (((TPB_UNIT_T)0x00000000) | TPB_UNAME_TIMERTIME | TPB_UBASE_BASE)
// Operation per second
#define TPB_UNIT_OPS    (((TPB_UNIT_T)0)  | TPB_UNAME_OPS | TPB_UBASE_BASE)
#define TPB_UNIT_KOPS   (((TPB_UNIT_T)3)  | TPB_UNAME_OPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MOPS   (((TPB_UNIT_T)6)  | TPB_UNAME_OPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GOPS   (((TPB_UNIT_T)9)  | TPB_UNAME_OPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TOPS   (((TPB_UNIT_T)12) | TPB_UNAME_OPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_POPS   (((TPB_UNIT_T)15) | TPB_UNAME_OPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_EOPS   (((TPB_UNIT_T)18) | TPB_UNAME_OPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZOPS   (((TPB_UNIT_T)21) | TPB_UNAME_OPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YOPS   (((TPB_UNIT_T)24) | TPB_UNAME_OPS | TPB_UBASE_DEC_EXP_P)
// Float-point operation per second
#define TPB_UNIT_FLOPS     (((TPB_UNIT_T)0)  | TPB_UNAME_FLOPS | TPB_UBASE_BASE)
#define TPB_UNIT_KFLOPS    (((TPB_UNIT_T)3)  | TPB_UNAME_FLOPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MFLOPS    (((TPB_UNIT_T)6)  | TPB_UNAME_FLOPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GFLOPS    (((TPB_UNIT_T)9)  | TPB_UNAME_FLOPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TFLOPS    (((TPB_UNIT_T)12) | TPB_UNAME_FLOPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_PFLOPS    (((TPB_UNIT_T)15) | TPB_UNAME_FLOPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_EFLOPS    (((TPB_UNIT_T)18) | TPB_UNAME_FLOPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZFLOPS    (((TPB_UNIT_T)21) | TPB_UNAME_FLOPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YFLOPS    (((TPB_UNIT_T)24) | TPB_UNAME_FLOPS | TPB_UBASE_DEC_EXP_P)
// Token per second
#define TPB_UNIT_TOKENPS     (((TPB_UNIT_T)0)  | TPB_UNAME_TOKENPS | TPB_UBASE_BASE)
#define TPB_UNIT_KTOKENPS    (((TPB_UNIT_T)3)  | TPB_UNAME_TOKENPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MTOKENPS    (((TPB_UNIT_T)6)  | TPB_UNAME_TOKENPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GTOKENPS    (((TPB_UNIT_T)9)  | TPB_UNAME_TOKENPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TTOKENPS    (((TPB_UNIT_T)12) | TPB_UNAME_TOKENPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_PTOKENPS    (((TPB_UNIT_T)15) | TPB_UNAME_TOKENPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ETOKENPS    (((TPB_UNIT_T)18) | TPB_UNAME_TOKENPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZTOKENPS    (((TPB_UNIT_T)21) | TPB_UNAME_TOKENPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YTOKENPS    (((TPB_UNIT_T)24) | TPB_UNAME_TOKENPS | TPB_UBASE_DEC_EXP_P)
// Transactions per second
#define TPB_UNIT_TPS    (((TPB_UNIT_T)0)  | TPB_UNAME_TPS | TPB_UBASE_BASE)
#define TPB_UNIT_KTPS   (((TPB_UNIT_T)3)  | TPB_UNAME_TPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MTPS   (((TPB_UNIT_T)6)  | TPB_UNAME_TPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GTPS   (((TPB_UNIT_T)9)  | TPB_UNAME_TPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TTPS   (((TPB_UNIT_T)12) | TPB_UNAME_TPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_PTPS   (((TPB_UNIT_T)15) | TPB_UNAME_TPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ETPS   (((TPB_UNIT_T)18) | TPB_UNAME_TPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZTPS   (((TPB_UNIT_T)21) | TPB_UNAME_TPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YTPS   (((TPB_UNIT_T)24) | TPB_UNAME_TPS | TPB_UBASE_DEC_EXP_P)
// Binary bytes per second derived from BITSIZE
#define TPB_UNIT_BITPS  (((TPB_UNIT_T)3)  | TPB_UNAME_BITPS | TPB_UBASE_BIN_EXP_N)
#define TPB_UNIT_BYTEPS (((TPB_UNIT_T)0)  | TPB_UNAME_BITPS | TPB_UBASE_BASE)
#define TPB_UNIT_KIBPS  (((TPB_UNIT_T)10) | TPB_UNAME_BITPS | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_MIBPS  (((TPB_UNIT_T)20) | TPB_UNAME_BITPS | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_GIBPS  (((TPB_UNIT_T)30) | TPB_UNAME_BITPS | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_TIBPS  (((TPB_UNIT_T)40) | TPB_UNAME_BITPS | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_PIBPS  (((TPB_UNIT_T)50) | TPB_UNAME_BITPS | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_EIBPS  (((TPB_UNIT_T)60) | TPB_UNAME_BITPS | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_ZIBPS  (((TPB_UNIT_T)70) | TPB_UNAME_BITPS | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_YIBPS  (((TPB_UNIT_T)80) | TPB_UNAME_BITPS | TPB_UBASE_BIN_EXP_P)
// Decimal bytes Yper second derived from DATASIZE
#define TPB_UNIT_BPS    (((TPB_UNIT_T)0)  | TPB_UNAME_DATAPS | TPB_UBASE_BASE)
#define TPB_UNIT_KBPS   (((TPB_UNIT_T)3)  | TPB_UNAME_DATAPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MBPS   (((TPB_UNIT_T)6)  | TPB_UNAME_DATAPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GBPS   (((TPB_UNIT_T)9)  | TPB_UNAME_DATAPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TBPS   (((TPB_UNIT_T)12) | TPB_UNAME_DATAPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_PBPS   (((TPB_UNIT_T)15) | TPB_UNAME_DATAPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_EBPS   (((TPB_UNIT_T)18) | TPB_UNAME_DATAPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZBPS   (((TPB_UNIT_T)21) | TPB_UNAME_DATAPS | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YBPS   (((TPB_UNIT_T)24) | TPB_UNAME_DATAPS | TPB_UBASE_DEC_EXP_P)
// Binary bytes per cycle derived from BITSIZE
#define TPB_UNIT_BITPCY  (((TPB_UNIT_T)3)  | TPB_UNAME_BITPCY | TPB_UBASE_BIN_EXP_N)
#define TPB_UNIT_BYTEPCY (((TPB_UNIT_T)0)  | TPB_UNAME_BITPCY | TPB_UBASE_BASE)
#define TPB_UNIT_KIBPCY  (((TPB_UNIT_T)10) | TPB_UNAME_BITPCY | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_MIBPCY  (((TPB_UNIT_T)20) | TPB_UNAME_BITPCY | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_GIBPCY  (((TPB_UNIT_T)30) | TPB_UNAME_BITPCY | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_TIBPCY  (((TPB_UNIT_T)40) | TPB_UNAME_BITPCY | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_PIBPCY  (((TPB_UNIT_T)50) | TPB_UNAME_BITPCY | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_EIBPCY  (((TPB_UNIT_T)60) | TPB_UNAME_BITPCY | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_ZIBPCY  (((TPB_UNIT_T)70) | TPB_UNAME_BITPCY | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_YIBPCY  (((TPB_UNIT_T)80) | TPB_UNAME_BITPCY | TPB_UBASE_BIN_EXP_P)
// Decimal bytes per cycle derived from DATASIZE
#define TPB_UNIT_BPCY    (((TPB_UNIT_T)0)  | TPB_UNAME_DATAPCY | TPB_UBASE_BASE)
#define TPB_UNIT_KBPCY   (((TPB_UNIT_T)3)  | TPB_UNAME_DATAPCY | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MBPCY   (((TPB_UNIT_T)6)  | TPB_UNAME_DATAPCY | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GBPCY   (((TPB_UNIT_T)9)  | TPB_UNAME_DATAPCY | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TBPCY   (((TPB_UNIT_T)12) | TPB_UNAME_DATAPCY | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_PBPCY   (((TPB_UNIT_T)15) | TPB_UNAME_DATAPCY | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_EBPCY   (((TPB_UNIT_T)18) | TPB_UNAME_DATAPCY | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZBPCY   (((TPB_UNIT_T)21) | TPB_UNAME_DATAPCY | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YBPCY   (((TPB_UNIT_T)24) | TPB_UNAME_DATAPCY | TPB_UBASE_DEC_EXP_P)
// Binary bytes per tick derived from BITSIZE
#define TPB_UNIT_BITPTICK  (((TPB_UNIT_T)3)  | TPB_UNAME_BITPTICK | TPB_UBASE_BIN_EXP_N)
#define TPB_UNIT_BYTEPTICK (((TPB_UNIT_T)0)  | TPB_UNAME_BITPTICK | TPB_UBASE_BASE)
#define TPB_UNIT_KIBPTICK  (((TPB_UNIT_T)10) | TPB_UNAME_BITPTICK | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_MIBPTICK  (((TPB_UNIT_T)20) | TPB_UNAME_BITPTICK | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_GIBPTICK  (((TPB_UNIT_T)30) | TPB_UNAME_BITPTICK | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_TIBPTICK  (((TPB_UNIT_T)40) | TPB_UNAME_BITPTICK | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_PIBPTICK  (((TPB_UNIT_T)50) | TPB_UNAME_BITPTICK | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_EIBPTICK  (((TPB_UNIT_T)60) | TPB_UNAME_BITPTICK | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_ZIBPTICK  (((TPB_UNIT_T)70) | TPB_UNAME_BITPTICK | TPB_UBASE_BIN_EXP_P)
#define TPB_UNIT_YIBPTICK  (((TPB_UNIT_T)80) | TPB_UNAME_BITPTICK | TPB_UBASE_BIN_EXP_P)
// Decimal bytes per tick derived from DATASIZE
#define TPB_UNIT_BPTICK    (((TPB_UNIT_T)0)  | TPB_UNAME_DATAPTICK | TPB_UBASE_BASE)
#define TPB_UNIT_KBPTICK   (((TPB_UNIT_T)3)  | TPB_UNAME_DATAPTICK | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_MBPTICK   (((TPB_UNIT_T)6)  | TPB_UNAME_DATAPTICK | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_GBPTICK   (((TPB_UNIT_T)9)  | TPB_UNAME_DATAPTICK | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_TBPTICK   (((TPB_UNIT_T)12) | TPB_UNAME_DATAPTICK | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_PBPTICK   (((TPB_UNIT_T)15) | TPB_UNAME_DATAPTICK | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_EBPTICK   (((TPB_UNIT_T)18) | TPB_UNAME_DATAPTICK | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_ZBPTICK   (((TPB_UNIT_T)21) | TPB_UNAME_DATAPTICK | TPB_UBASE_DEC_EXP_P)
#define TPB_UNIT_YBPTICK   (((TPB_UNIT_T)24) | TPB_UNAME_DATAPTICK | TPB_UBASE_DEC_EXP_P)

#endif /* TPB_UNITDEFS_H */